- name: Install required system packages
  hosts: "*"
  become: true
  tasks:
    - name: Refresh update_cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: 'yes'

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
