- name: Configure Cardano Files
  hosts: "*"
  tasks:
    - name: Run Portainer Agent Container
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent:2.16.2
        state: started
        recreate: true
        detach: true
        restart: true
        restart_policy: "always"
        ports:
          - 9001:9001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
