---
- name: Refresh Packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: 'yes'
  become: true

- name: Install System Packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true
  become: true
