- name: Download the latest Cardano ledger snapshot
  hosts: "*"
  tasks:
      - name: Query Snapshot
        ansible.builtin.uri:
            url: https://downloads.csnapshots.io/snapshots/mainnet/mainnet-db-snapshot.json
            return_content: true
            body_format: json
        changed_when: false
        register: result

      - name: Get Snapshot State
        ansible.builtin.set_fact:
            snapshot_state: "{{ result | json_query('json[0].file_name') }}"

      - name: Save Snapshot
        ansible.builtin.get_url:
            url: https://downloads.csnapshots.io/snapshots/mainnet/{{ snapshot_state }}
            mode: 0644
            dest: ~/{{ snapshot_state }}

    # Alternative way to do this (does not require Ansible Galaxy Community.General)
    # - name: Query Snapshot
    #   ansible.builtin.shell: curl -s https://downloads.csnapshots.io/snapshots/mainnet/mainnet-db-snapshot.json | jq -r '.[].file_name'
    #   register: snapshot_state
